// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD5DG7xPX6su_xhTFF2nUIeTugJgHbMsE',
    appId: '1:225667979023:web:1281a88ad277f1e6c8907a',
    messagingSenderId: '225667979023',
    projectId: 'tea-go-app',
    authDomain: 'tea-go-app.firebaseapp.com',
    storageBucket: 'tea-go-app.firebasestorage.app',
    measurementId: 'G-FJNYLJ6K9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37mIOFr6SbcePUv0RIsXKw97rJIyrUXg',
    appId: '1:225667979023:android:c9b36c658e66479dc8907a',
    messagingSenderId: '225667979023',
    projectId: 'tea-go-app',
    storageBucket: 'tea-go-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2jEh-afN3kPczIWKxsjHiXNyPYi_rVM',
    appId: '1:225667979023:ios:77ea0c1425b55bc2c8907a',
    messagingSenderId: '225667979023',
    projectId: 'tea-go-app',
    storageBucket: 'tea-go-app.firebasestorage.app',
    iosBundleId: 'com.example.teaGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd2jEh-afN3kPczIWKxsjHiXNyPYi_rVM',
    appId: '1:225667979023:ios:77ea0c1425b55bc2c8907a',
    messagingSenderId: '225667979023',
    projectId: 'tea-go-app',
    storageBucket: 'tea-go-app.firebasestorage.app',
    iosBundleId: 'com.example.teaGoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD5DG7xPX6su_xhTFF2nUIeTugJgHbMsE',
    appId: '1:225667979023:web:be28e124dee33690c8907a',
    messagingSenderId: '225667979023',
    projectId: 'tea-go-app',
    authDomain: 'tea-go-app.firebaseapp.com',
    storageBucket: 'tea-go-app.firebasestorage.app',
    measurementId: 'G-8Z5BPC9J01',
  );
}
